<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/4/21 0021
 * Time: 20:07
 */

namespace frontend\models;

use yii\base\Model;

class ContentForm extends Model
{



    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }



}